### ISSUE TITLE
Interested in added custom parts

### ISSUE THREAD

**Issue by nkondapa** [visinf/funnybirds#2]
Hi, 

I enjoyed reading your work! I was hoping to get more instruction on how I might be able to add and render custom parts that go beyond what is present here? 

Thank you!

**Comment by robinhesse** [comment]
Hi,

Thank you for your interest in our work! The parts for rendering can be found in render/js/three.js-master/examples/data/XAI. Here you can also add your custom parts. To render your custom scene, please follow the instructions in render/README.md. Once this is working, you can adjust the scene by adjusting render/page.html.

I hope this helps.
Best,
Robin

**Comment by nkondapa** [comment]
Thanks, actually my question was about what software was used to make the parts, but I have found that it is blender. Thanks.
