### ISSUE TITLE
GUI based custom image creation/Instructions to create custom images

### ISSUE THREAD

**Issue by LokeshBadisa** [visinf/funnybirds#4]
1. Can you add GUI based bird creation? If it is already there, could you please point me to it? 
2. Can you add instructions on what to modify to create custom bird images? If it is already there, could you please point me to it?

**Comment by robinhesse** [comment]
Hi,

Thanks for your interest in our work!

I am not planning to add a GUI based bird creation. However, you can visualize and modify the birds by adjusting the link parameters and opening the visualization in your browser. Please see [here](https://github.com/visinf/funnybirds/tree/main/render) for details. There you should also find the relevant information to create custom bird images.

Best,
Robin
